### ISSUE TITLE
Allow jumping to different points in the timelime

### ISSUE THREAD

**Issue by s-ol** [rm-code/logivi#10]

**Comment by rm-code** [comment]
Thanks for your suggestion. Do you mean a key which makes the log run "backwards" or do you just mean the possibility to jump back in time?

**Comment by s-ol** [comment]
Either would be fine. While you're at it, can The playback speed be modified?

**Comment by rm-code** [comment]
You can already set the delay between commits in the config file ( commitDelay = 0.2 ). Setting it to zero will load a new commit every frame.

EDIT: Should probably add a keybinding for that too.

**Comment by rm-code** [comment]
Partially added this in https://github.com/rm-code/logivi/commit/660f9ed0d8295603498b3333e3f0a30585629fc5 which allows you to go back in time one step at a time. Next thing I'm going to add is a "rewind" function which makes the log run backwards automatically.

_Jumping_ back and forth to certain points in time will probably take a little longer to be implemented.

**Comment by rm-code** [comment]
Working on this at the moment. One of the biggest issues is what to once a user jumps to a certain place in time. The simple solution would be to destroy the graph and simply start a "new" one from that point in time. Problem with this is, we would get a lot of "missed" modifications etc. because files who would be there simply aren't.

A better solution would be to go through all commits in the log from the current to the selected point in time while ignoring commits which just modify a file. Based on the information of the add and delete commits we could then create the graph layout at the selected time. Of course this can take quite some time if the repo is huge.

**Comment by s-ol** [comment]
In other media streams there are snapshots in regular intervals with delta-changes inbetween, but that would require more elaborate resource generation in the first place (would end up with more than one `git log`)

**Comment by rm-code** [comment]
@S0lll0s That's what it does (at least if I understand your comment correctly). Basically it maps the total commits of the log to the steps in the timeline and whenever you click one of the steps it takes the delta (only additions and deletions) and generates the graph for that point in time.

**Comment by s-ol** [comment]
What I meant to say is that things like video encodings store "absolute" states every X frames so you can jump directly to them, and then apply all the following deltas to get to the exact time:

```
                                 A            X
| - - - - - - - | - - - - - - - | - - - - - - - | - - - - - - - |            ( | = absolute state; - = delta/patch )
```

now, when you want to display state `X`, you first jump to `A` directly and then apply the remaining deltas, instead of playing through the hole log from the beginnning.

**Comment by rm-code** [comment]
Ah yes, now I understand. This certainly is doable, but are there any benefits besides saving a few ms?

**Comment by s-ol** [comment]
I doubt there is a real use for it here, It sounded like you were worried about performance though.
I'm pretty sure the performance overhead is not worth the generation hassle.

**Comment by rm-code** [comment]
@S0lll0s I was indeed! Mostly because I just wasn't sure how I was going to do it and how performance heavy it would turn out. This is probably the biggest project I have worked on so far and a lot of the stuff I do is based on trial and error and I'm glad for every little new thing I can learn.

So thanks for your feedback - much appreciated!
